apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-go-apps
spec:
  generators:
    - git:
        repoURL: https://github.com/dumunari/gitops-essentials.git
        revision: application-set-helm
        files:
        - path: "apps/**/config.yaml"
  template:
    metadata:
      name: 'dev-{{application}}'
    spec:
      project: go-apps
      source:
        repoURL: "{{repoUrl}}"
        targetRevision: appset-helm
        path: "{{application}}-helm-chart"
        helm:
          valueFiles:
            - "values-dev.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated: {}
      