apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-apps-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: go-apps
  source:
    repoURL: https://github.com/dumunari/gitops-essentials.git
    targetRevision: application-set
    path: application-set.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}