apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dp.yaml
- svc.yaml

images:
- name: webserver
  newName: emunari/webserver
  newTag: d8f6c4818b928dfec48c6d829da23aba9ef3dd55
